[project]
name = "iam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "async-lru>=2.0.4",
    "fastapi>=0.115.12",
    "keystoneauth1==4.5.0",
    "python-keystoneclient==4.4.0",
    "uvicorn>=0.33.0",
]
