APP_NAME = 'IAM'
APP_HOST = '0.0.0.0'
APP_PORT = 8080
WORKERS = 1
DEBUG = True
WEBROOT = '/api'

OPENSTACK_KEYSTONE_URL = 'http://127.0.0.1:5000/v3'
OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = 'default'
OPENSTACK_SSL_NO_VERIFY = True
OPENSTACK_SSL_CACERT = False
OPENSTACK_ENDPOINT_TYPE = 'public'
OPENSTACK_OWNER_ROLE = 'owner'

AUTHENTICATION_HEADER = 'X-Authentication'
IDENTITY_HEADER = 'X-Identity'
